# Generated by Django 2.1.3 on 2018-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='matiere',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
