# Generated by Django 2.1.3 on 2018-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_teacher_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='matiere',
            field=models.CharField(max_length=20),
        ),
    ]
